const ALPHAMAT_DATA = {
  "animals": [
    {
      "id": "animal_0",
      "type": "animal",
      "alphabet": "A",
      "name": "Alligator (Magar / Indian River Crocodile)",
      "scientificName": "Alligator mississippiensis / Crocodilus",
      "category": "Reptile",
      "color": "Dark Olive Green & Armored Brown Scales",
      "diet": "Carnivore — River fish, water birds & turtles",
      "habitat": "Rivers, lakes & marshy wetlands across India and Maharashtra",
      "lifespan": "35 – 50 years",
      "weight": "200 – 450 kg (440 – 990 lbs)",
      "superpower": "Super Strong Jaw Bite & Silent Underwater Swimming",
      "conservation": "Protected Indian River Reptile",
      "funFact": "Alligators and crocodiles can hold their breath underwater for up to two hours without coming up for air!",
      "description": "The Alligator (and India's native Crocodile or Magarmach / Gharial) is a powerful, armored river reptile found across Indian wetlands, lakes, and rivers! They have bumpy green-and-brown scales, webbed swimming feet, and a super strong jaw lined with sharp teeth. When swimming, they leave only their eyes and nostrils above the water so they can watch the river silently.",
      "image": "Alligator.jpg",
      "model": "Alligator.glb",
      "hasRealModel": true,
      "hasRealImage": true
    },
    {
      "id": "animal_1",
      "type": "animal",
      "alphabet": "A",
      "name": "Asiatic Lion (Sher / Indian Forest Lion)",
      "scientificName": "Panthera leo persica",
      "category": "Mammal",
      "color": "Golden Tawny Brown & Dark Mane",
      "diet": "Carnivore — Deer & wild jungle animals",
      "habitat": "Gir Forest & Indian dry savannahs",
      "lifespan": "15 – 18 years",
      "weight": "160 – 190 kg (350 – 420 lbs)",
      "superpower": "Loud Royal Roar & Strong Hunting Paws",
      "conservation": "Protected Indian Pride",
      "funFact": "The Asiatic Lion is found nowhere else in the wild in the entire world except India!",
      "description": "The Asiatic Lion is the majestic forest king of India! Male lions have a proud golden-brown mane around their face and make a loud roar that can be heard from miles away inside the forest. They live together in loving family groups called prides where everyone takes care of the little lion cubs.",
      "image": "lion.jpg",
      "model": "lion.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "animal_2",
      "type": "animal",
      "alphabet": "A",
      "name": "Asiatic Elephant (Hathi)",
      "scientificName": "Elephas maximus",
      "category": "Mammal",
      "color": "Slate Gray with Pink Ear Spots",
      "diet": "Herbivore — Bananas, sugarcane, bamboo & grass",
      "habitat": "Western Ghats, Sahyadri hills & Indian jungles",
      "lifespan": "60 – 70 years",
      "weight": "3,000 – 5,000 kg (6,600 – 11,000 lbs)",
      "superpower": "Long Trunk Hand & Gentle Elephant Memory",
      "conservation": "Sacred Indian Heritage Animal",
      "funFact": "Indian elephants love bathing in rivers and spraying cool water over their backs with their long trunks!",
      "description": "The Asiatic Elephant is the beloved, gentle giant of India's forests and the Western Ghats! They use their long, flexible trunk just like a hand to pick sweet bananas, eat sugarcane, and drink cool river water. Elephants are very wise, loving animals that always protect their little calves.",
      "image": "elephant.jpg",
      "model": "elephant.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "animal_3",
      "type": "animal",
      "alphabet": "A",
      "name": "Ant (Cheenti / Mungi)",
      "scientificName": "Formicidae",
      "category": "Insect",
      "color": "Black, Red & Dark Brown",
      "diet": "Omnivore — Sweet crumbs, grains & garden seeds",
      "habitat": "Underground tunnels across Indian gardens and villages",
      "lifespan": "1 – 3 years",
      "weight": "1 – 5 mg (Tiny and light)",
      "superpower": "Super Strength & Teamwork",
      "conservation": "Abundant Everywhere in India",
      "funFact": "An ant can lift objects up to 50 times its own body weight without getting tired!",
      "description": "Ants (known as Cheenti in Hindi and Mungi in Marathi) are hard-working little insects found in every garden and field! They live together in big underground tunnel homes called colonies where thousands of ants work as a team. They talk to each other using scent trails to find sweet food and care for baby ants.",
      "image": "ant.jpg",
      "model": "ant.glb",
      "hasRealModel": true,
      "hasRealImage": true
    },
    {
      "id": "animal_4",
      "type": "animal",
      "alphabet": "A",
      "name": "Alpaca (Mountain Wool Friend)",
      "scientificName": "Vicugna pacos",
      "category": "Mammal",
      "color": "White, Fawn, Silver & Brown",
      "diet": "Herbivore — Green mountain grass & hay",
      "habitat": "Cool mountain pastures and hill stations",
      "lifespan": "15 – 20 years",
      "weight": "55 – 65 kg (120 – 140 lbs)",
      "superpower": "Super Soft Fluffy Wool & Gentle Padded Feet",
      "conservation": "Gentle Farm Animal",
      "funFact": "Alpacas hum gently to talk to their friends and babies!",
      "description": "Alpacas are gentle, fluffy mountain animals famous for having some of the softest, warmest wool in the whole world. They are very friendly, love grazing on green mountain grass with their herd, and have soft padded feet that don't hurt the ground.",
      "image": "alpaca.jpg",
      "model": "alpaca.glb",
      "hasRealModel": true,
      "hasRealImage": true
    },
    {
      "id": "animal_5",
      "type": "animal",
      "alphabet": "B",
      "name": "Bengal Tiger (Bagh)",
      "scientificName": "Panthera tigris tigris",
      "category": "Mammal",
      "color": "Bright Orange Coat with Black Stripes & White Tummy",
      "diet": "Carnivore — Forest deer, wild boar & sambar",
      "habitat": "Tadoba, Pench & Indian jungle sanctuaries",
      "lifespan": "12 – 15 years in the wild",
      "weight": "180 – 260 kg (400 – 570 lbs)",
      "superpower": "Stealthy Jungle Pounce & Swimming in Cool Lakes",
      "conservation": "India's National Animal — Protected & Growing",
      "funFact": "Every single tiger has a completely unique stripe pattern, just like human fingerprints!",
      "description": "The Royal Bengal Tiger is India's National Animal and the most famous wildlife treasure of Maharashtra's Tadoba Forest! With its bright orange coat and dark black stripes, the tiger moves silently through the jungle trees. Unlike most cats, tigers love swimming in forest ponds and lakes during hot summer afternoons.",
      "image": "tiger.jpg",
      "model": "tiger.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "animal_6",
      "type": "animal",
      "alphabet": "B",
      "name": "Barking Deer (Bhekar)",
      "scientificName": "Muntiacus muntjak",
      "category": "Mammal",
      "color": "Chestnut Reddish-Brown & Golden Fawn",
      "diet": "Herbivore — Forest berries, tender leaves & fallen fruits",
      "habitat": "Sahyadri hills, Western Ghats & dense Maharashtra woods",
      "lifespan": "10 – 14 years",
      "weight": "18 – 28 kg (40 – 62 lbs)",
      "superpower": "Loud Barking Alarm Call & Fast Forest Jumping",
      "conservation": "Abundant across Sahyadri Forests",
      "funFact": "When the Barking Deer sees danger in the jungle, it makes a loud 'Woof-Woof' sound just like a dog!",
      "description": "The Barking Deer (called Bhekar in Maharashtra) is a small, shy deer found throughout the Sahyadri mountains and Western Ghats. It gets its famous name because whenever it senses a tiger or leopard nearby, it lets out a loud barking alarm call that sounds just like a dog barking to warn all the forest animals!",
      "image": "barkingdeer.jpg",
      "model": "barkingdeer.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "animal_7",
      "type": "animal",
      "alphabet": "B",
      "name": "Black Bear (Sloth Bear / Bhalu)",
      "scientificName": "Melursus ursinus",
      "category": "Mammal",
      "color": "Shaggy Black Fur with White Chest Mark",
      "diet": "Omnivore — Termites, wild berries, honey & forest fruits",
      "habitat": "Sanjay Gandhi National Park, Tadoba & Indian hills",
      "lifespan": "20 – 25 years",
      "weight": "90 – 145 kg (200 – 320 lbs)",
      "superpower": "Suction Snout for Eating Termites & Tree Climbing",
      "conservation": "Protected Indian Jungle Bear",
      "funFact": "Sloth Bears can suck up termites right out of the ground making a loud vacuum sound!",
      "description": "The Indian Sloth Bear (called Bhalu in Hindi and Asval in Marathi) is a shaggy black bear with a cute white U-shaped mark on its chest. They live right in Maharashtra's forests and hill sanctuaries, using their long curved claws to open termite mounds and climb trees to eat sweet honey and wild jamun berries.",
      "image": "Bear.jpg",
      "model": "Bear.glb",
      "hasRealModel": true,
      "hasRealImage": true
    },
    {
      "id": "animal_8",
      "type": "animal",
      "alphabet": "B",
      "name": "Buffalo (Water Buffalo / Bhais)",
      "scientificName": "Bubalus bubalis",
      "category": "Mammal",
      "color": "Charcoal Black & Slate Gray",
      "diet": "Herbivore — Green farm grass, clover & hay",
      "habitat": "Village farms, ponds & riverbanks across India",
      "lifespan": "20 – 25 years",
      "weight": "500 – 900 kg (1,100 – 2,000 lbs)",
      "superpower": "Wide Curved Horns & Rich Wholesome Milk",
      "conservation": "Beloved Indian Farm Helper",
      "funFact": "Water buffalo love spending hot summer afternoons sitting happily inside cool muddy village ponds!",
      "description": "The Water Buffalo (Bhais in Hindi and Mhais in Marathi) is one of the strongest and most helpful farm animals across every village in India! They have wide curved horns and love splashing around in cool ponds to keep their skin comfortable. Indian farmers care deeply for them because they give thick, nutritious milk used for making curd, paneer, and ghee.",
      "image": "Buffalo.jpg",
      "model": "Buffalo.glb",
      "hasRealModel": true,
      "hasRealImage": true
    },
    {
      "id": "animal_9",
      "type": "animal",
      "alphabet": "B",
      "name": "Bee (Madhumakhi)",
      "scientificName": "Anthophila",
      "category": "Insect",
      "color": "Bright Yellow & Velvet Black Stripes",
      "diet": "Herbivore — Flower nectar and yellow pollen",
      "habitat": "Flower gardens, farm fields & tree hives across India",
      "lifespan": "6 weeks (Workers) to 5 years (Queen)",
      "weight": "0.1 g (Tiny buzzing insect)",
      "superpower": "Making Golden Honey & Pollinating Farm Crops",
      "conservation": "Essential Garden & Farm Helper",
      "funFact": "To make just one spoon of honey, bees visit thousands of pretty flowers across the garden!",
      "description": "Honeybees (called Madhumakhi in Hindi and Madhmashi in Marathi) are wonderful buzzing insects that fly from flower to flower across Indian fields and gardens. They drink sweet flower nectar and take yellow pollen home to their wax beehive. By visiting flowers, bees help Indian mango trees, sunflower fields, and farm vegetables grow delicious fruit.",
      "image": "Bee.jpg",
      "model": "Bee.glb",
      "hasRealModel": true,
      "hasRealImage": true
    },
    {
      "id": "animal_10",
      "type": "animal",
      "alphabet": "C",
      "name": "Cow (Gaay / Gaai)",
      "scientificName": "Bos taurus indicus",
      "category": "Mammal",
      "color": "White, Brown, Black & Spotted Cream",
      "diet": "Herbivore — Green meadow grass, clover & farm hay",
      "habitat": "Every household, village & farm across India and Maharashtra",
      "lifespan": "18 – 22 years",
      "weight": "400 – 600 kg (880 – 1,320 lbs)",
      "superpower": "Giving Fresh Nutritious Milk & Loving Motherly Bond",
      "conservation": "Revered & Beloved Indian Farm Animal",
      "funFact": "Indian cows (Zebu cows) have a gentle shoulder hump and long soft ears that help them stay cool in hot weather!",
      "description": "The Cow (called Gaay in Hindi and Gaai in Marathi) is the most beloved, gentle, and respected farm animal across India! They spend sunny days grazing on green pasture grass and give us fresh, wholesome milk every day. Families across Indian villages treat cows with great love and care, celebrating them during festivals like Pola and Pongal.",
      "image": "Cow.jpg",
      "model": "Cow.glb",
      "hasRealModel": true,
      "hasRealImage": true
    },
    {
      "id": "animal_11",
      "type": "animal",
      "alphabet": "C",
      "name": "Chital Deer (Spotted Deer / Harin)",
      "scientificName": "Axis axis",
      "category": "Mammal",
      "color": "Golden Fawn Brown with Bright White Spots",
      "diet": "Herbivore — Tender forest leaves, green grass & wild fruits",
      "habitat": "Sanjay Gandhi National Park, Tadoba & Indian forests",
      "lifespan": "12 – 16 years",
      "weight": "50 – 85 kg (110 – 187 lbs)",
      "superpower": "Graceful Leaping & Branching Velvet Antlers",
      "conservation": "Abundant across Indian Wildlife Parks",
      "funFact": "The Chital Deer is famous for keeping its beautiful white spots across its back its entire adult life!",
      "description": "The Chital (or Indian Spotted Deer, called Harin in Marathi) is one of the most beautiful and graceful deer found in every forest across India and Maharashtra! Their golden-brown coat is covered in bright white spots that look like dappled sunlight in the woods. Male spotted deer grow tall, majestic branching antlers that shed and regrow every year.",
      "image": "deer.jpg",
      "model": "deer.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "animal_12",
      "type": "animal",
      "alphabet": "C",
      "name": "Cat (Billi / Manjar)",
      "scientificName": "Felis catus",
      "category": "Mammal",
      "color": "Orange Tabby, Calico, Black & White",
      "diet": "Carnivore — Milk, fish & pet treats",
      "habitat": "Cozy homes, city verandas & courtyards across India",
      "lifespan": "14 – 20 years",
      "weight": "3.5 – 5.5 kg (8 – 12 lbs)",
      "superpower": "Night Vision, Soft Paws & Soothing Purring",
      "conservation": "Beloved Indian Household Pet",
      "funFact": "Cats sleep up to 16 hours every day and love finding warm patches of sunlight on the veranda to nap!",
      "description": "Domestic Cats (called Billi in Hindi and Manjar in Marathi) are playful, soft, and friendly companions living inside homes across India! They have long sensitive whiskers, padded paws for silent walking, and bright eyes that can see clearly in pitch dark. When cuddled gently, they make a happy, soothing purr sound that warms everyone's heart.",
      "image": "Cat.jpg",
      "model": "Cat.glb",
      "hasRealModel": true,
      "hasRealImage": true
    },
    {
      "id": "animal_13",
      "type": "animal",
      "alphabet": "C",
      "name": "Camel (Oont / Unta)",
      "scientificName": "Camelus dromedarius",
      "category": "Mammal",
      "color": "Sandy Tan & Warm Fawn Brown",
      "diet": "Herbivore — Desert thorns, dry grass & hay",
      "habitat": "Dry sandy plains of Rajasthan, Gujarat & Maharashtra borders",
      "lifespan": "40 – 50 years",
      "weight": "400 – 650 kg (880 – 1,430 lbs)",
      "superpower": "Desert Survival & Wide Sand-Walking Paws",
      "conservation": "Famous Indian Desert Helper",
      "funFact": "A camel has thick double eyelashes to keep blowing desert sand completely out of its eyes during windstorms!",
      "description": "The Camel (called Oont in Hindi and Unta in Marathi) is famous across India as the 'Ship of the Desert'! They have a large hump on their back that stores emergency fat so they can travel across hot sandy lands for many days without getting tired or thirsty. Their wide padded feet let them walk smoothly on soft desert sand.",
      "image": "Camel.jpg",
      "model": "Camel.glb",
      "hasRealModel": true,
      "hasRealImage": true
    },
    {
      "id": "animal_14",
      "type": "animal",
      "alphabet": "C",
      "name": "Chinkara (Indian Gazelle)",
      "scientificName": "Gazella bennettii",
      "category": "Mammal",
      "color": "Warm Sandy Reddish-Brown & White Tummy",
      "diet": "Herbivore — Dry grass, desert shrubs & leaves",
      "habitat": "Dry scrublands, hills & plains of Maharashtra and India",
      "lifespan": "12 – 15 years",
      "weight": "20 – 25 kg (44 – 55 lbs)",
      "superpower": "High-Speed Gazelle Sprinting & Living Without Water for Days",
      "conservation": "Protected Indian Grassland Gazelle",
      "funFact": "The Chinkara gazelle can get all the water it needs just from the morning dew drops on desert leaves!",
      "description": "The Chinkara (or Indian Gazelle) is a small, timid, and incredibly fast deer-like gazelle found roaming across the dry hills and open grasslands of Maharashtra and central India. Both male and female chinkaras have beautiful, curved black horns. When startled, they can leap high into the air and sprint across the plains with breathtaking agility.",
      "image": "chinkara.jpg",
      "model": "chinkara.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "animal_15",
      "type": "animal",
      "alphabet": "D",
      "name": "Dog (Kutta / Moti)",
      "scientificName": "Canis lupus familiaris",
      "category": "Mammal",
      "color": "Golden Blonde, Brown, Black & White Spotted",
      "diet": "Omnivore — Home food, milk, rice & pet treats",
      "habitat": "Every home, farm & neighborhood across India and Maharashtra",
      "lifespan": "10 – 15 years",
      "weight": "10 – 35 kg (22 – 77 lbs)",
      "superpower": "Unconditional Loyalty & Super Sniffing Nose",
      "conservation": "India's Best Household Guardian & Friend",
      "funFact": "Indian Pariah dogs (Desi dogs) are one of the healthiest, smartest, and oldest natural dog breeds in the world!",
      "description": "Dogs (called Kutta in Hindi and Kutra in Marathi, lovingly named Moti or Sheru in Indian homes) are the most loyal and friendly household companions in the world! They guard Indian homes with alert ears and wag their tails cheerfully whenever children come home from school. Their super sniffing nose can detect scents thousands of times better than humans.",
      "image": "dog.jpg",
      "model": "dog.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "animal_16",
      "type": "animal",
      "alphabet": "D",
      "name": "Donkey (Gadha / Gadhav)",
      "scientificName": "Equus africanus asinus",
      "category": "Mammal",
      "color": "Gray, Chestnut Brown & White with Big Ears",
      "diet": "Herbivore — Farm hay, dry grass, carrots & apples",
      "habitat": "Village farms, brick kilns & countryside roads across India",
      "lifespan": "25 – 35 years",
      "weight": "180 – 250 kg (400 – 550 lbs)",
      "superpower": "Big Listening Ears & Sure-Footed Hill Climbing",
      "conservation": "Patient & Hard-Working Village Helper",
      "funFact": "A donkey's large ears can hear another donkey calling out from over 3 miles away across the village!",
      "description": "The Donkey (called Gadha in Hindi and Gadhav in Marathi) is a gentle, patient, and hard-working farm friend with very big, soft ears! For centuries across Indian villages and mountain paths, donkeys have helped farmers carry grain and supplies safely along rocky paths without slipping. They are very careful, smart thinkers.",
      "image": "donkey.jpg",
      "model": "donkey.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "animal_17",
      "type": "animal",
      "alphabet": "D",
      "name": "Duck (Badak / Badakh)",
      "scientificName": "Anas platyrhynchos",
      "category": "Bird",
      "color": "White, Emerald Green Head & Brown Feathers",
      "diet": "Omnivore — Pond weeds, seeds, grains & water bugs",
      "habitat": "Village ponds, lakes & rivers across Maharashtra and India",
      "lifespan": "8 – 12 years",
      "weight": "1.0 – 1.6 kg (2.2 – 3.5 lbs)",
      "superpower": "Waterproof Feathers & Webbed Swimming Feet",
      "conservation": "Cheerful Indian Pond Bird",
      "funFact": "Ducks have special oil on their feathers that keeps them completely dry even after swimming underwater!",
      "description": "Ducks (called Badak in Hindi and Badakh in Marathi) are cheerful water birds that swim happily across village ponds and rivers while making a cheerful 'Quack-quack!' sound. They have orange webbed feet that work like swimming paddles to help them glide smoothly across the water. Little yellow ducklings follow their watchful mother across the pond in a neat line.",
      "image": "duck.jpg",
      "model": "duck.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "animal_18",
      "type": "animal",
      "alphabet": "D",
      "name": "Dolphin (Gangetic River Dolphin / Souns)",
      "scientificName": "Platanista gangetica",
      "category": "Mammal",
      "color": "Sleek River Gray & Blue",
      "diet": "Carnivore — Freshwater river fish & shrimp",
      "habitat": "Indian rivers & coastal waters of Maharashtra",
      "lifespan": "25 – 30 years",
      "weight": "150 – 170 kg (330 – 370 lbs)",
      "superpower": "Echolocation Sonar Navigation & Gentle Leaping",
      "conservation": "India's National Aquatic Animal — Protected",
      "funFact": "India's freshwater river dolphins use sound clicks (echolocation) to swim and find fish in deep river waters!",
      "description": "The Indian Dolphin (including the Gangetic Dolphin and coastal dolphins near Maharashtra's Konkan beaches) is a super smart, friendly water mammal! Even though they swim in the water, dolphins are warm-blooded mammals that swim up to the surface to take a breath of fresh air through a blowhole right on top of their heads.",
      "image": "dolphin.jpg",
      "model": "dolphin.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "animal_19",
      "type": "animal",
      "alphabet": "D",
      "name": "Dugong (Sea Cow)",
      "scientificName": "Dugong dugon",
      "category": "Mammal",
      "color": "Gentle Slate Gray & Ocean Blue",
      "diet": "Herbivore — Underwater seagrass & marine plants",
      "habitat": "Coastal Indian ocean waters & Andaman seas",
      "lifespan": "50 – 70 years",
      "weight": "250 – 400 kg (550 – 880 lbs)",
      "superpower": "Gentle Underwater Swimming & Seagrass Grazing",
      "conservation": "Rare & Protected Marine Mammal in India",
      "funFact": "Dugongs are called 'Sea Cows' because they spend all day peacefully grazing on underwater green meadows of seagrass!",
      "description": "The Dugong (lovingly known as the Indian Sea Cow) is a rare, gentle marine mammal that lives in calm coastal waters around India. They have a round, friendly face and a dolphin-like tail that helps them glide slowly through underwater seagrass meadows. They are very peaceful, harmless ocean swimmers protected by Indian wildlife laws.",
      "image": "dugong.jpg",
      "model": "dugong.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "animal_20",
      "type": "animal",
      "alphabet": "E",
      "name": "Elephant (Indian Elephant / Hathi)",
      "scientificName": "Elephas maximus indicus",
      "category": "Mammal",
      "color": "Slate Gray with Pink Ear Spots",
      "diet": "Herbivore — Bananas, sugarcane, bamboo & forest leaves",
      "habitat": "Western Ghats, Sahyadri forests & Indian national parks",
      "lifespan": "60 – 70 years",
      "weight": "3,000 – 5,000 kg (6,600 – 11,000 lbs)",
      "superpower": "Long Flexible Trunk & Elephant Wisdom",
      "conservation": "India's National Heritage Animal — Protected",
      "funFact": "An Indian elephant's trunk has over 40,000 muscles and can pick up a single coin off the ground!",
      "description": "The Indian Elephant (called Hathi in Hindi and Hatti in Marathi) is the most magnificent, wise, and beloved giant of India's forests! They use their long, flexible trunk just like a hand to gather sweet sugarcane, eat bunches of bananas, and give friendly trumpeting calls. Elephant families share deep emotional bonds and always travel together in herds.",
      "image": "elephant.jpg",
      "model": "elephant.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "animal_21",
      "type": "animal",
      "alphabet": "E",
      "name": "Eagle (Crested Serpent Eagle / Garuda)",
      "scientificName": "Spilornis cheela",
      "category": "Bird",
      "color": "Dark Brown Wings with Yellow Beak & Crest",
      "diet": "Carnivore — Snakes, lizards & small forest mice",
      "habitat": "Western Ghats, Sahyadri mountain crags & Indian forests",
      "lifespan": "20 – 25 years",
      "weight": "1.2 – 1.8 kg (2.6 – 4 lbs)",
      "superpower": "Telescopic Eagle Eyesight & High Mountain Soaring",
      "conservation": "Thriving Indian Bird of Prey",
      "funFact": "Eagles have eyesight nearly eight times sharper than humans, spotting little field mice from high up in the clouds!",
      "description": "The Crested Serpent Eagle (revered across Indian culture and mythology as Garuda) is a majestic bird of prey that soars high above the Western Ghats and Sahyadri hills of Maharashtra! They have strong wings, sharp curved talons, and a distinctive feather crown on their heads. They glide effortlessly on warm rising air currents while watching over the forest.",
      "image": "eagle.jpg",
      "model": "eagle.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "animal_22",
      "type": "animal",
      "alphabet": "E",
      "name": "Earthworm (Kenchua / Gandhul)",
      "scientificName": "Lumbricina",
      "category": "Invertebrate",
      "color": "Pinkish Red & Moist Earth Brown",
      "diet": "Decomposer — Soil nutrients, fallen leaves & organic compost",
      "habitat": "Moist farm soil and garden beds across Maharashtra and India",
      "lifespan": "4 – 8 years",
      "weight": "1 – 10 g (Little garden helper)",
      "superpower": "Turning Soil into Rich Natural Fertilizer (Vermicompost)",
      "conservation": "The Indian Farmer's Best Friend",
      "funFact": "Earthworms breathe oxygen right through their moist pink skin while wiggling underground inside garden dirt!",
      "description": "Earthworms (called Kenchua in Hindi and Gandhul in Marathi) are celebrated as the Indian farmer's absolute best friend! They wiggle gently through the moist soil of Maharashtra's farms and vegetable gardens, creating tiny tunnels that let fresh air and rainwater reach plant roots. By turning old leaves into natural fertilizer, they help Indian farm crops grow tall and healthy.",
      "image": "earthworm.jpg",
      "model": "earthworm.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "animal_23",
      "type": "animal",
      "alphabet": "E",
      "name": "Eel (Indian River Eel)",
      "scientificName": "Anguilla bengalensis",
      "category": "Fish",
      "color": "Olive Green, Yellow & Deep River Gray",
      "diet": "Carnivore — Small river fish, shrimp & water insects",
      "habitat": "Rivers, streams and coastal estuaries of Maharashtra & India",
      "lifespan": "15 – 20 years",
      "weight": "1.5 – 4 kg (3.3 – 8.8 lbs)",
      "superpower": "Snake-Like Swimming & Smooth Slippery Scales",
      "conservation": "Fascinating Indian Freshwater Fish",
      "funFact": "Indian river eels can wiggle across wet grass during monsoon rains to move from one pond to another!",
      "description": "The Indian River Eel (or Bengal Eel) is a long, smooth freshwater fish that looks just like a swimming snake as it wiggles gracefully through rivers and streams across India! Their skin is covered in smooth, microscopic scales that make them super slippery and fast inside the water while searching for tiny river shrimp.",
      "image": "eel.jpg",
      "model": "eel.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "animal_24",
      "type": "animal",
      "alphabet": "E",
      "name": "Egret (White Crane / Bagla / Bagla Bird)",
      "scientificName": "Ardea alba",
      "category": "Bird",
      "color": "Pure Snow White Feathers with Yellow Beak",
      "diet": "Carnivore — Paddy field fish, frogs & water insects",
      "habitat": "Rice paddy fields, village ponds & rivers across India",
      "lifespan": "15 – 22 years",
      "weight": "0.7 – 1.5 kg (1.5 – 3.3 lbs)",
      "superpower": "Standing Perfectly Still in Water & Lightning-Fast Beak Catching",
      "conservation": "Abundant & Elegant Indian Wading Bird",
      "funFact": "Egrets love riding gently on the backs of grazing water buffaloes to catch little bugs that hop out of the grass!",
      "description": "The Great Egret (known across India as the White Crane or Bagla) is an elegant, pure white wading bird with long slender legs and a bright yellow beak! You can see them standing patiently like statues right in the middle of green rice paddy fields and village ponds across Maharashtra. When a little fish swims by, they dart their long beak down like an arrow!",
      "image": "egret.jpg",
      "model": "egret.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "animal_25",
      "type": "animal",
      "alphabet": "F",
      "name": "Fox (Indian Desert Fox / Lomdi)",
      "scientificName": "Vulpes vulpes pusilla",
      "category": "Mammal",
      "color": "Golden Tawny Fur with White Chest & Bushy Tail",
      "diet": "Omnivore — Berries, field mice, beetles & fallen fruit",
      "habitat": "Scrublands, open fields & hills across Maharashtra and India",
      "lifespan": "5 – 8 years in the wild",
      "weight": "3 – 6 kg (6.6 – 13 lbs)",
      "superpower": "Big Sensitive Ears & Clever Pouncing",
      "conservation": "Abundant across Indian Open Meadows",
      "funFact": "An Indian fox uses its big bushy tail like a warm umbrella when resting under the bushes!",
      "description": "The Indian Fox (called Lomdi in Hindi and Kokha / Kolha in Marathi) is a clever, agile wild animal with pointed ears and a famous fluffy bushy tail! They live in cozy underground burrows across open fields and scrublands across Maharashtra. They make cute yipping barks and have super sharp hearing that lets them listen for tiny field mice running across the grass.",
      "image": "fox.jpg",
      "model": "fox.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "animal_26",
      "type": "animal",
      "alphabet": "F",
      "name": "Frog (Indian Monsoon Frog / Mendhak)",
      "scientificName": "Hoplobatrachus tigerinus",
      "category": "Amphibian",
      "color": "Bright Emerald Green & Yellow during Monsoon",
      "diet": "Carnivore — Flying bugs, mosquitoes & garden insects",
      "habitat": "Monsoon ponds, paddy fields & green gardens across India",
      "lifespan": "7 – 10 years",
      "weight": "50 – 250 g (Jumping pond hopper)",
      "superpower": "High Jumping Legs & Sticky Mosquito-Catching Tongue",
      "conservation": "Essential Monsoon Garden Friend",
      "funFact": "Male Indian bullfrogs turn bright golden yellow during the monsoon rains to sing loud 'Ribbit' songs!",
      "description": "The Indian Monsoon Frog (called Mendhak in Hindi and Beduk in Marathi) is the hopping green champion of India's rainy season! When the monsoon rains fall over Maharashtra, these frogs fill village ponds and green gardens with cheerful choruses of ribbit songs. They use their long, sticky tongues to catch mosquitoes and garden bugs right out of the air.",
      "image": "frog.jpg",
      "model": "frog.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "animal_27",
      "type": "animal",
      "alphabet": "F",
      "name": "Fish (Rohu / Indian River Fish / Machli)",
      "scientificName": "Labeo rohita",
      "category": "Fish",
      "color": "Shimmering Silver & River Gray",
      "diet": "Omnivore — River algae, water plants & plankton",
      "habitat": "Freshwater rivers, lakes & village ponds across India",
      "lifespan": "8 – 10 years",
      "weight": "1 – 5 kg (2.2 – 11 lbs)",
      "superpower": "Breathing Underwater with Gills & Fin Steering",
      "conservation": "Most Popular Indian Freshwater Fish",
      "funFact": "Rohu fish swim together in big shimmering groups called schools to keep each other safe inside the river!",
      "description": "The Rohu (known across India as Machli or Masa) is the most famous and popular freshwater fish swimming inside Indian rivers, lakes, and village ponds! They have shimmering silver scales, balancing fins, and breathe oxygen directly from the water using gills on their cheeks. They swim gracefully through underwater plants and are a vital part of Indian aquatic life.",
      "image": "fish.jpg",
      "model": "fish.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "animal_28",
      "type": "animal",
      "alphabet": "F",
      "name": "Flying Squirrel (Indian Giant Flying Squirrel)",
      "scientificName": "Petaurista philippensis",
      "category": "Mammal",
      "color": "Reddish Chestnut Brown with White Underbelly",
      "diet": "Herbivore — Tree nuts, forest fruits, bark & leaves",
      "habitat": "Western Ghats, Sahyadri forests & Bhimashankar Sanctuary",
      "lifespan": "10 – 15 years",
      "weight": "1.2 – 1.8 kg (2.6 – 4 lbs)",
      "superpower": "Gliding 200 Feet Through the Night Air Between Trees",
      "conservation": "Protected Western Ghats Tree Squirrel",
      "funFact": "The Indian Giant Flying Squirrel doesn't have wings like a bird, but it spreads furry skin flaps between its paws to glide through the trees!",
      "description": "The Indian Giant Flying Squirrel (called Shekharu's gliding cousin in Maharashtra's Bhimashankar forest) is an amazing treetop animal! While it doesn't fly like a bird, it has a special furry blanket of skin stretched between its front and back paws. When it leaps from a tall jungle tree at night, it opens its paws to glide up to 200 feet through the air like a furry parachute!",
      "image": "flyingsquirrel.jpg",
      "model": "flyingsquirrel.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "animal_29",
      "type": "animal",
      "alphabet": "F",
      "name": "Falcon (Shaheen Falcon / Baaj)",
      "scientificName": "Falco peregrinus peregrinator",
      "category": "Bird",
      "color": "Slate Blue-Gray Wings with Russet Red Chest",
      "diet": "Carnivore — Flying birds caught in mid-air",
      "habitat": "Western Ghats sea cliffs, hill forts & high rocky peaks of India",
      "lifespan": "12 – 16 years",
      "weight": "0.7 – 1.4 kg (1.5 – 3 lbs)",
      "superpower": "High-Speed Aerial Diving (Swooping over 200 mph)",
      "conservation": "Protected Indian Flying Champion",
      "funFact": "The Shaheen Falcon often nests right on the high rocky towers of ancient historical hill forts across Maharashtra!",
      "description": "The Shaheen Falcon (known in Hindi as Baaj or Shaheen) is India's fastest flying bird of prey! They build their nests high up on rocky mountain cliffs and atop the ancient historical hill forts of Maharashtra. When soaring through the sky, they can fold their wings and zoom down through the air like a rocket at breathtaking speeds over 200 miles per hour.",
      "image": "falcon.jpg",
      "model": "falcon.glb",
      "hasRealModel": false,
      "hasRealImage": false
    }
  ],
  "fruits": [
    {
      "id": "fruit_0",
      "type": "fruit",
      "alphabet": "A",
      "name": "Alphonso Mango (Hapus / Amba)",
      "scientificName": "Mangifera indica 'Alphonso'",
      "category": "Fruit",
      "color": "Golden Saffron Yellow with Sunny Blush",
      "taste": "Rich, creamy, super sweet, and world-famous tropical nectar",
      "vitamins": "Loaded with Vitamin C, Vitamin A (Beta-Carotene) & Sweet Energy",
      "benefits": "Boosts immunity, keeps eyes glowing and bright & India's favorite summer fruit",
      "season": "Indian Summer harvest (April through June)",
      "origin": "Grown in the sunny Konkan coast of Maharashtra (Ratnagiri and Devgad) for centuries",
      "culinaryUses": "Fresh sweet mango slices, Aamras Puri, mango milkshake & summer ice cream",
      "funFact": "The Alphonso Mango from Maharashtra is celebrated around the entire world as the undisputed 'King of Mangoes'!",
      "description": "The Alphonso Mango (lovingly called Hapus in Marathi and Aam in Hindi) is the pride of Maharashtra's Konkan coast! Grown in Ratnagiri and Devgad, slicing open a golden Hapus reveals the sweetest, creamiest, saffron-colored fruit pulp in the world. During Indian summer vacations, enjoying bowls of chilled Aamras with puris is every child's favorite memory.",
      "image": "mango.jpg",
      "model": "mango.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "fruit_1",
      "type": "fruit",
      "alphabet": "A",
      "name": "Apple (Seb / Safarchand)",
      "scientificName": "Malus domestica",
      "category": "Fruit",
      "color": "Crisp Ruby Red & Golden Green",
      "taste": "Crunchy, sweet, and bursting with refreshing apple juice",
      "vitamins": "Abundant in Vitamin C, Pectin Fiber & Clean Playground Fuel",
      "benefits": "Keeps teeth strong and clean, aids tummy digestion & easy school lunch snack",
      "season": "Autumn mountain harvest across Simla and Kashmir (Enjoyed year-round)",
      "origin": "Grown in the cool Himalayan foothill orchards of India for generations",
      "culinaryUses": "Lunchbox apple wedges, fruit salad, apple juice & morning breakfast crunch",
      "funFact": "Eating a crunchy apple in the morning gives you just as much clean natural wake-up energy as drinking a glass of milk!",
      "description": "The Apple (called Seb in Hindi and Safarchand in Marathi) is one of the most popular and crunchy fruits sold in every Indian fruit market! Grown in the cool hill orchards of Simla and Kashmir, biting into a fresh red apple makes a loud, fun snap sound. It is packed with healthy fruit fiber and natural sweetness that keeps children strong and active.",
      "image": "apple.jpg",
      "model": "Apple.glb",
      "hasRealModel": true,
      "hasRealImage": true
    },
    {
      "id": "fruit_2",
      "type": "fruit",
      "alphabet": "A",
      "name": "Amla (Indian Gooseberry)",
      "scientificName": "Phyllanthus emblica",
      "category": "Fruit",
      "color": "Bright Emerald Green & Yellow-Green",
      "taste": "Crisp, sour, and refreshing (Leaves a magical sweet aftertaste when drinking water!)",
      "vitamins": "Extraordinary Vitamin C content (Up to 30x more than oranges!) & Antioxidants",
      "benefits": "Makes hair thick and shiny, supercharges immunity to stop winter coughs & purifies body",
      "season": "Autumn and Winter harvest across Indian forests and farms",
      "origin": "Revered across India for over 5,000 years in traditional Ayurvedic wellness",
      "culinaryUses": "Sweet Amla Murabba (candy preserve), Chyawanprash, fresh immunity juice & pickles",
      "funFact": "If you bite into a sour Amla berry and then immediately drink a glass of plain water, the water tastes like sweet sugar magic on your tongue!",
      "description": "Amla (known around the world as Indian Gooseberry and Avala in Marathi) is a bright green, round fruit celebrated across India for thousands of years as the ultimate health treasure! Every single berry has up to 30 times more pure Vitamin C than an orange. Mothers and grandmothers love giving sweet Amla Murabba or Chyawanprash to children in winter to keep their immunity super strong.",
      "image": "amla.jpg",
      "model": "amla.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "fruit_3",
      "type": "fruit",
      "alphabet": "A",
      "name": "Anjeer (Indian Fig)",
      "scientificName": "Ficus carica",
      "category": "Fruit",
      "color": "Soft Purple & Green with Sweet Honeyed Inside",
      "taste": "Jammy, sweet, soft, and filled with delicate crunchy little seeds",
      "vitamins": "Rich in Calcium (for strong bones), Iron, Potassium & Digestive Fiber",
      "benefits": "Builds super strong bones and teeth, keeps tummy healthy & gives athletic energy",
      "season": "Summer and Autumn harvest across Maharashtra farms (Pune and Saswad)",
      "origin": "Cultivated across Maharashtra's Pune district (Purandar Anjeer) with great pride",
      "culinaryUses": "Fresh sweet snacks, Anjeer Barfi, Kaju Anjeer sweets & dried winter energy snacks",
      "funFact": "Purandar Anjeer from Pune, Maharashtra is so famous for its sweet honeyed taste that it has an official Indian Geographical indication tag!",
      "description": "Anjeer (known in English as Fig) is a soft, sweet, nutritious fruit grown in abundance right in Maharashtra's Pune district (Purandar Anjeer)! When you slice open an Anjeer, the inside looks like rose-pink jam filled with hundreds of tiny, delicate seeds that give a gentle crunch. It is packed with natural calcium and iron, making it a favorite Indian festival sweet and healthy snack.",
      "image": "anjeer.jpg",
      "model": "anjeer.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "fruit_4",
      "type": "fruit",
      "alphabet": "A",
      "name": "Apricot (Khubani / Jardalu)",
      "scientificName": "Prunus armeniaca",
      "category": "Fruit",
      "color": "Velvet Golden Orange with Rosy Cheek",
      "taste": "Sweet, soft, honeyed, and smooth with soft fuzzy skin",
      "vitamins": "High in Vitamin A (for healthy eyes), Vitamin C & Potassium",
      "benefits": "Helps children see clearly, keeps skin glowing & wonderful winter dried snack",
      "season": "Summer fresh harvest (Sold across Indian dry fruit markets all year as Khubani)",
      "origin": "Grown in northern Indian hill orchards and enjoyed across Indian households",
      "culinaryUses": "Khubani ka Meetha (Hyderabad royal dessert), dried fruit snacks & summer fruit bowls",
      "funFact": "Dried apricot (Khubani) is used to make one of India's most famous and delicious royal desserts called 'Khubani ka Meetha'!",
      "description": "Apricots (known as Khubani or Jardalu across Indian fruit and dry fruit markets) are golden-orange fruits with soft, fuzzy velvet skin that feels just like a little peach! Inside their juicy, honey-sweet flesh sits a smooth wooden pit. Because they are super rich in Vitamin A, snacking on fresh or dried Khubani helps keep children's eyes bright and healthy.",
      "image": "Apricot.jpg",
      "model": "apricot.glb",
      "hasRealModel": false,
      "hasRealImage": true
    },
    {
      "id": "fruit_5",
      "type": "fruit",
      "alphabet": "B",
      "name": "Banana (Kela / Keli)",
      "scientificName": "Musa paradisiaca",
      "category": "Fruit",
      "color": "Bright Yellow Peel with Sweet Creamy Inside",
      "taste": "Sweet, tropical, soft, and naturally creamy",
      "vitamins": "Abundant in Potassium, Vitamin B6, Vitamin C & Healthy Carbs",
      "benefits": "Stops muscle cramps during playtime, gives instant clean energy & super easy to digest",
      "season": "Year-round harvest across Maharashtra (Famous Jalgaon and Vasai bananas)",
      "origin": "Grown across Indian farms for thousands of years as a sacred, auspicious fruit",
      "culinaryUses": "School lunch snack, Shikran (banana with milk & sugar), banana chips & fruit salad",
      "funFact": "Jalgaon district in Maharashtra grows so many sweet, delicious bananas that it is famously called the 'Banana City of India'!",
      "description": "Bananas (called Kela in Hindi and Keli in Marathi) are Maharashtra's number one favorite everyday fruit! Grown across Jalgaon and Vasai, they come pre-wrapped in their own clean yellow peel. Biting into a sweet, creamy banana gives children instant energy for running, swimming, and school games while keeping their tummy happy.",
      "image": "Banana.jpg",
      "model": "banana.glb",
      "hasRealModel": true,
      "hasRealImage": true
    },
    {
      "id": "fruit_6",
      "type": "fruit",
      "alphabet": "B",
      "name": "Ber (Indian Jujube / Bor)",
      "scientificName": "Ziziphus mauritiana",
      "category": "Fruit",
      "color": "Shiny Green, Golden Yellow & Russet Red",
      "taste": "Crunchy, sweet-and-sour, juicy, and super refreshing like a mini apple!",
      "vitamins": "Packed with Vitamin C, Antioxidants, Calcium & Natural Energy",
      "benefits": "Fights off winter coughs, strengthens teeth and gums & beloved Indian childhood treat",
      "season": "Winter and early Spring harvest (Sold outside schools and across Indian markets during festivals)",
      "origin": "Traditional Indian fruit tree celebrated across Indian folklore and Makar Sankranti festivals",
      "culinaryUses": "Fresh crunchy snacking with a pinch of black salt (Kala Namak) & Makar Sankranti Bor-Nahan",
      "funFact": "During Makar Sankranti in Maharashtra, little children celebrate 'Bor-Nahan' where sweet Ber fruits and candies are showered over them for good luck and health!",
      "description": "Ber (known in Marathi as Bor and in English as Indian Jujube) is one of India's most cherished and nostalgic childhood fruits! They look like shiny little green or russet-red miniature apples that grow on thorny garden trees. When you bite into a fresh Ber with a pinch of black salt, it has an incredible, crunchy sweet-and-sour crunch that every Indian child loves.",
      "image": "ber.jpg",
      "model": "ber.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "fruit_7",
      "type": "fruit",
      "alphabet": "B",
      "name": "Bael (Wood Apple / Belphal)",
      "scientificName": "Aegle marmelos",
      "category": "Fruit",
      "color": "Hard Golden-Green Woody Shell with Sweet Aromatic Orange Pulp",
      "taste": "Sweet, aromatic, and cooling with notes of marmalade and honey",
      "vitamins": "Rich in Vitamin C, Riboflavin, Beta-Carotene & Cooling Electrolytes",
      "benefits": "The ultimate Indian summer coolant, soothes tummy digestion & protects against sunstroke",
      "season": "Spring and Summer harvest across Indian temple gardens and farms",
      "origin": "Revered across India for millennia as a sacred tree whose leaves and fruits hold great spiritual value",
      "culinaryUses": "Famous cooling Bel ka Sharbat (Bael juice with jaggery and water) & sweet fruit preserves",
      "funFact": "A Bael fruit has a shell so hard like wood that grown-ups have to crack it open with a rolling pin or stone to get to the sweet orange fruit inside!",
      "description": "Bael (known as Wood Apple or Belphal in Hindi and Bel in Marathi) is a sacred, unique Indian fruit covered in a hard woody shell! When summer heat arrives across India, cracking open a Bael fruit reveals sweet, golden-orange aromatic pulp. Mixing this sweet pulp with cold water and jaggery makes 'Bel ka Sharbat,' India's most famous cooling drink to protect against summer heat.",
      "image": "bael.jpg",
      "model": "bael.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "fruit_8",
      "type": "fruit",
      "alphabet": "B",
      "name": "Blackberry (Indian Jamun / Jambul)",
      "scientificName": "Syzygium cumini",
      "category": "Fruit",
      "color": "Glossy Deep Dark Purple & Violet Black",
      "taste": "Sweet, tangy, refreshing, and astringent fruit juice",
      "vitamins": "Loaded with Iron, Vitamin C, Potassium & Powerful Purple Antioxidants",
      "benefits": "Purifies blood, keeps heart and blood sugar healthy & turns your tongue purple!",
      "season": "Summer and Monsoon harvest right across Maharashtra trees",
      "origin": "Native Indian tree whose cool shade and sweet purple fruits have blessed Indian roads for centuries",
      "culinaryUses": "Fresh summer snacking with Kala Namak, refreshing Jamun shots & fruit popsicles",
      "funFact": "Eating a handful of fresh Indian Jamun fruits magically turns your entire tongue and lips deep violet purple for hours during playtime!",
      "description": "Jamun (known in English as Indian Blackberry or Jambul in Marathi) is India's favorite dark purple summer fruit! Growing on large shade trees across Maharashtra's roads and gardens, these glossy purple berries fall right as the summer rains begin. Biting into a fresh Jamun with a pinch of black salt releases sweet-and-tangy purple juice that famously turns every child's tongue bright purple!",
      "image": "blackberry.jpg",
      "model": "blackberry.glb",
      "hasRealModel": true,
      "hasRealImage": true
    },
    {
      "id": "fruit_9",
      "type": "fruit",
      "alphabet": "B",
      "name": "Blueberry (Nilbadari / Berry)",
      "scientificName": "Vaccinium corymbosum",
      "category": "Fruit",
      "color": "Deep Sapphire Blue with Frosted Shimmer",
      "taste": "Sweet, crisp-skinned, juicy, and refreshingly clean",
      "vitamins": "Supercharged with Vitamin C, Vitamin K, Manganese & Brain Power Antioxidants",
      "benefits": "Makes memory and focus super sharp, keeps eyes healthy & protects body cells",
      "season": "Available fresh in Indian fruit stores and gourmet markets all year",
      "origin": "Globally famous superberry widely enjoyed across Indian modern breakfast tables",
      "culinaryUses": "Blueberry pancakes, fruit yogurt topping, school fruit cups & morning smoothies",
      "funFact": "Blueberries are one of the very few naturally blue fruits found anywhere in the entire world!",
      "description": "Blueberries (known as Nilbadari or Blue Berries in Indian fruit shops) are tiny, round blue jewels celebrated by doctors and teachers as brain-boosting superfruits! They have a delicate blue frosted skin and sweet, clean fruit juice inside. Dropping a handful of fresh blueberries into morning cornflakes, oatmeal, or curd is a delicious way to build a super smart brain.",
      "image": "blueberry.jpg",
      "model": "blueberry.glb",
      "hasRealModel": true,
      "hasRealImage": true
    },
    {
      "id": "fruit_10",
      "type": "fruit",
      "alphabet": "C",
      "name": "Custard Apple (Sitafal / Sharifa)",
      "scientificName": "Annona squamosa",
      "category": "Fruit",
      "color": "Bumpy Emerald Green Skin with Creamy White Inside",
      "taste": "Super sweet, velvety, creamy, and tastes just like natural vanilla ice cream custard!",
      "vitamins": "Abundant in Vitamin C, Magnesium, Potassium, Calcium & Natural Energy",
      "benefits": "Builds healthy muscles, cools the body, gives sweet natural energy & easy to eat with a spoon",
      "season": "Autumn and Winter harvest right across Maharashtra (Famous Beed and Purandar Sitafal)",
      "origin": "Thriving across rocky hills and farm gardens in Maharashtra for centuries",
      "culinaryUses": "Eating fresh with a spoon, world-famous Sitafal Rabdi, Sitafal ice cream & milkshakes",
      "funFact": "Maharashtra grows the largest and sweetest Custard Apples (Sitafal) in India, and eating one raw feels just like eating vanilla custard ice cream!",
      "description": "Custard Apple (known across Maharashtra and India by its beloved name Sitafal or Sharifa) is one of the sweetest and most delicious fruits on Earth! Covered in bumpy green skin, gently breaking open a ripe Sitafal reveals soft, creamy white segments holding shiny black seeds. Every spoonful of sweet white Sitafal pulp tastes just like chilled vanilla custard ice cream right from nature.",
      "image": "sitafal.jpg",
      "model": "sitafal.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "fruit_11",
      "type": "fruit",
      "alphabet": "C",
      "name": "Cheeku (Sapodilla / Chikoo)",
      "scientificName": "Manilkara zapota",
      "category": "Fruit",
      "color": "Earthy Brown Skin with Sweet Caramel-Brown Inside",
      "taste": "Super sweet, grainy-soft, and tastes exactly like brown sugar caramel or malai peda!",
      "vitamins": "Loaded with Vitamin C, Vitamin A, Dietary Fiber, Calcium & Instant Energy Sugar",
      "benefits": "Gives instant playground energy, aids healthy tummy digestion & builds strong bones",
      "season": "Harvested year-round across Maharashtra (World-famous Dahanu-Gholvad Chikoo)",
      "origin": "Cultivated across coastal Maharashtra (Palghar/Dahanu) with official Indian GI Tag recognition",
      "culinaryUses": "Fresh sweet fruit wedges, famous Chikoo Milkshake, Chikoo halwa & ice cream",
      "funFact": "Dahanu and Gholvad in coastal Maharashtra grow India's sweetest Chikoos, where the fruit tastes so sweet it feels like eating brown sugar candy!",
      "description": "Cheeku (also written as Chikoo or Sapodilla) is Maharashtra's favorite sweet brown fruit! Grown extensively across Dahanu and Gholvad near Mumbai, Cheeku looks like a round brown potato on the outside. But when you slice it open, the soft, grainy-brown inside is bursting with natural honeyed sweetness that tastes just like caramel, jaggery, and sweet milk barfi!",
      "image": "cheeku.jpg",
      "model": "cheeku.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "fruit_12",
      "type": "fruit",
      "alphabet": "C",
      "name": "Coconut (Nariyal / Naral)",
      "scientificName": "Cocos nucifera",
      "category": "Fruit",
      "color": "Green Tender Coconut or Brown Shell with Snow-White Malai",
      "taste": "Nutty, sweet, refreshing coconut water and tender white coconut malai",
      "vitamins": "High in Natural Electrolytes, Potassium, MCT Healthy Fats & Minerals",
      "benefits": "India's best summer hydration drink, gives clean brain fuel & keeps hair thick and black",
      "season": "Harvested year-round across Maharashtra's Konkan coast and Indian beaches",
      "origin": "Revered as 'Kalpavriksha' (the wish-fulfilling tree) in Indian tradition for thousands of years",
      "culinaryUses": "Drinking tender coconut water (Nariyal Pani), coconut chutney, Modak stuffing (Naralachi Wadi) & curry",
      "funFact": "In Maharashtra during Ganesh Chaturthi, sweet grated coconut (Naral) and jaggery are cooked together to make Ukadiche Modak, Lord Ganesha's favorite sweet!",
      "description": "Coconut (called Nariyal in Hindi and Naral in Marathi) is the most sacred and versatile fruit of Maharashtra's Konkan coast! When green and tender, drinking fresh Nariyal Pani from a straw is nature's most refreshing, mineral-rich sports drink to beat the summer sun. Inside sits pure white, tender malai that is grated to make delicious Indian chutneys and sweet Modak stuffing.",
      "image": "Coconut.jpg",
      "model": "Coconut.glb",
      "hasRealModel": true,
      "hasRealImage": true
    },
    {
      "id": "fruit_13",
      "type": "fruit",
      "alphabet": "C",
      "name": "Cherry (Sweet Red Cherry)",
      "scientificName": "Prunus avium",
      "category": "Fruit",
      "color": "Glossy Ruby Red & Dark Burgundy",
      "taste": "Super sweet, crisp, and bursting with red fruit juice",
      "vitamins": "Rich in Vitamin C, Potassium & Natural Sleep Melatonin",
      "benefits": "Helps tired legs recover after running and helps children sleep cozily at night",
      "season": "Summer harvest in northern Indian hill orchards (Enjoyed all year on cakes)",
      "origin": "Cherished red orchard fruit celebrated across Indian bakeries and desserts",
      "culinaryUses": "Birthday cake toppings, Black Forest pastry, fruit custard & fresh sweet snacking",
      "funFact": "Every single child in India knows and loves the bright red sweet cherry that sits right on top of delicious birthday pastries and ice cream sundaes!",
      "description": "Cherries are cheerful, ruby-red fruits with a cute little green stem that kids love! They grow in cool orchard gardens and have a crisp skin bursting with sweet red fruit juice inside. In India, cherries are the absolute star of every celebration, sitting proudly on top of birthday cakes, fruit salads, and creamy ice cream sundaes.",
      "image": "Cherry.jpg",
      "model": "Cherry.glb",
      "hasRealModel": true,
      "hasRealImage": true
    },
    {
      "id": "fruit_14",
      "type": "fruit",
      "alphabet": "C",
      "name": "Cantaloupe (Kharbuja / Sweet Melon)",
      "scientificName": "Cucumis melo",
      "category": "Fruit",
      "color": "Beige Woven Net Rind with Bright Sweet Orange Inside",
      "taste": "Juicy, super sweet, and fragrant with honeyed melon nectar",
      "vitamins": "Supercharged with Vitamin A (Beta-Carotene), Vitamin C & Pure Melon Water",
      "benefits": "Hydrates body instantly during hot Indian summers, keeps eyes healthy & cools the tummy",
      "season": "Indian Summer melon harvest (Sold across every fruit stall from March to June)",
      "origin": "Traditional cooling summer melon grown across Indian riverbanks and sunny farms",
      "culinaryUses": "Chilled melon wedges, Kharbuja juice with ice, fruit salad & summer afternoon snacks",
      "funFact": "Kharbuja is over 90% pure cool water, making it one of the absolute best fruits to eat after playing in the hot summer sun!",
      "description": "Cantaloupe (called Kharbuja in Hindi and Marathi) is India's favorite cooling summer melon! It has a neat woven beige net pattern on the outside shell, and when sliced open, reveals a glowing, sweet orange interior brimming with cool, refreshing melon juice. Eating chilled Kharbuja wedges on a warm afternoon quenches thirst and keeps children full of energy.",
      "image": "cantaloupe.jpg",
      "model": "cantaloupe.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "fruit_15",
      "type": "fruit",
      "alphabet": "D",
      "name": "Date (Khajoor / Khajur)",
      "scientificName": "Phoenix dactylifera",
      "category": "Fruit",
      "color": "Rich Caramel Mahogany Brown",
      "taste": "Super sweet, chewy, and tastes just like natural caramel or toffee candy!",
      "vitamins": "Abundant in Iron (builds red blood cells), Potassium, Magnesium & Energy Fiber",
      "benefits": "Gives instant running energy, builds strong blood and bones & healthy natural sugar",
      "season": "Available fresh and dried (Khajoor / Kharik) across every Indian market all year",
      "origin": "Grown in sunny desert oases (Kutch/Rajasthan) and enjoyed in Indian homes for millennia",
      "culinaryUses": "Healthy natural candy snack, Khajoor rolls, dry fruit laddoo & winter milk tonics",
      "funFact": "Khajoor has so much healthy natural energy that eating just two dates before soccer or cricket practice gives you power for the whole game!",
      "description": "Dates (known across every Indian household as Khajoor in Hindi and Khajur / Kharik in Marathi) are nature's original caramel candy! Sold in every Indian market, these sweet, chewy brown fruits grow in big bunches on tall palm trees under the warm sun. Because they are packed with natural iron and energy, mothers love giving sweet Khajoor to children for school boxes and winter strength.",
      "image": "date.jpg",
      "model": "date.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "fruit_16",
      "type": "fruit",
      "alphabet": "D",
      "name": "Dragon Fruit (Kamalam / Pitaya)",
      "scientificName": "Selenicereus undatus",
      "category": "Fruit",
      "color": "Bright Neon Pink Skin with White & Black Seeded Inside",
      "taste": "Mildly sweet, crisp, and super refreshing like a juicy kiwi fruit",
      "vitamins": "Rich in Vitamin C, Magnesium, Prebiotic Fiber & Pink Antioxidants",
      "benefits": "Keeps tummy digestion super healthy, boosts immunity & looks super exciting and fun",
      "season": "Summer and Autumn harvest across Maharashtra farms (Solapur, Pune, Baramati farms)",
      "origin": "Given the official Sanskrit Indian name 'Kamalam' (lotus fruit) and widely farmed across India today",
      "culinaryUses": "Pink fruit salad cubes, refreshing summer smoothies, ice cream & healthy breakfast bowls",
      "funFact": "In India, Dragon Fruit is officially named 'Kamalam' because its beautiful pink outer scales open up just like a blooming lotus flower!",
      "description": "Dragon Fruit (officially named Kamalam in India because its pink scales look like a lotus flower) is one of the most exciting fruits grown right across Maharashtra's farms today! When you slice open the bright pink outer skin, the inside is crisp white or magenta fruit speckled with thousands of tiny, crunchy edible black seeds. It is super refreshing, light, and full of healthy tummy fiber.",
      "image": "dragonfruit.jpg",
      "model": "dragonfruit.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "fruit_17",
      "type": "fruit",
      "alphabet": "D",
      "name": "Dusehri Mango (Dussehri Aam)",
      "scientificName": "Mangifera indica 'Dussehri'",
      "category": "Fruit",
      "color": "Smooth Golden Yellow & Green Skin",
      "taste": "Super sweet, aromatic, juicy, and completely fiberless golden mango nectar",
      "vitamins": "Loaded with Vitamin C, Vitamin A (Beta-Carotene), Potassium & Natural Fruit Sugar",
      "benefits": "Refreshes summer energy, promotes glowing healthy skin & loved by mango lovers across India",
      "season": "Peak Indian Summer mango harvest (June and July)",
      "origin": "Famous Indian heritage mango originating from village Dussehri near Lucknow over 200 years ago",
      "culinaryUses": "Squeezing and drinking sweet mango juice right out of the skin, mango shakes & sliced dessert",
      "funFact": "Dusehri mangoes have such soft, juicy inside pulp that children love rolling them gently in their hands to soften the inside and drinking the sweet juice right from the top!",
      "description": "Dusehri Mango is one of India's most famous and beloved summer mango varieties! Known for its elongated shape and smooth golden skin, Dusehri has thin skin, a small stone, and super sweet, juicy pulp with no rough fibers. Children across India love softening a ripe Dusehri in their hands, making a small hole at the top, and sucking out the sweet, golden mango juice just like a natural juice pack!",
      "image": "dusehrimango.jpg",
      "model": "dusehrimango.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "fruit_18",
      "type": "fruit",
      "alphabet": "D",
      "name": "Dark Plum (Alubukhara / Indian Plum)",
      "scientificName": "Prunus domestica",
      "category": "Fruit",
      "color": "Deep Purple & Blue Outer Skin with Golden Inside",
      "taste": "Sweet, juicy, and delightfully tangy near the skin",
      "vitamins": "Rich in Vitamin C, Potassium, Dietary Fiber & Purple Antioxidants",
      "benefits": "Aids smooth tummy digestion, quenches thirst on warm days & keeps blood healthy",
      "season": "Summer and Monsoon harvest across Indian fruit stores",
      "origin": "Beloved Indian orchard stone fruit enjoyed both fresh and dried across traditional kitchens",
      "culinaryUses": "Fresh whole fruit snacks, sweet Alubukhara chutney, fruit salads & summer compotes",
      "funFact": "When Dark Plums (Alubukhara) are simmered with sugar and spices in India, they make the most delicious sweet-and-sour chutney served at weddings and celebrations!",
      "description": "The Dark Plum (known across Indian markets and kitchens as Alubukhara) is a round, smooth stone fruit with deep purple-blue skin and golden interior flesh! Biting into a ripe summer plum delivers a splash of sweet fruit juice balanced by just the right amount of tanginess. Inside sits a little wooden pit that pops right out after you enjoy the sweet fruit.",
      "image": "darkplum.jpg",
      "model": "darkplum.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "fruit_19",
      "type": "fruit",
      "alphabet": "D",
      "name": "Dwarf Banana (Elaichi Kela / Velchi Kela)",
      "scientificName": "Musa acuminata 'Dwarf'",
      "category": "Fruit",
      "color": "Bright Golden Yellow Peel with Extra Sweet Creamy Inside",
      "taste": "Super sweet, creamy, and naturally flavored with a hint of cardamom (Elaichi)",
      "vitamins": "Abundant in Potassium, Vitamin B6, Vitamin C & Quick Playground Fuel",
      "benefits": "Perfect kid-sized snack, stops playtime muscle cramps & super easy for little hands to peel",
      "season": "Harvested year-round across Maharashtra (Famous Vasai Velchi Kela)",
      "origin": "Miniature sweet banana variety prized across Maharashtra and Indian coastal farms",
      "culinaryUses": "Mini school lunchbox snacks, fruit skewers, Shikran & instant clean playground energy",
      "funFact": "In Maharashtra, these baby bananas are called 'Velchi Kela' (Cardamom Bananas) because they are so naturally sweet they taste like they were spiced with cardamom!",
      "description": "Dwarf Bananas (famously known across Maharashtra as Velchi Kela and across India as Elaichi Kela or Baby Bananas) are miniature, kid-sized yellow bananas! Even though they are only about 3 to 4 inches long, they fit perfectly right into a child's hand and pack twice the sweet honeyed flavor of regular large bananas. Peeling one gives children an instant, super sweet healthy snack anytime.",
      "image": "dwarfbanana.jpg",
      "model": "dwarfbanana.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "fruit_20",
      "type": "fruit",
      "alphabet": "E",
      "name": "Elaichi Banana (Small Sweet Banana / Velchi)",
      "scientificName": "Musa paradisiaca 'Cardamom'",
      "category": "Fruit",
      "color": "Golden Yellow Miniature Peel",
      "taste": "Super sweet, dense, creamy, and fragrant with natural cardamom notes",
      "vitamins": "Rich in Potassium, Vitamin B6, Vitamin C & Healthy Fruit Carbs",
      "benefits": "Kid-approved mini snack, gives clean playground energy & very gentle on the tummy",
      "season": "Year-round harvest across Maharashtra and Indian fruit stores",
      "origin": "Traditional miniature banana grown in coastal Maharashtra gardens",
      "culinaryUses": "School tiffin box treat, morning breakfast snack & fruit salad bowls",
      "funFact": "Elaichi Bananas have such thin, soft yellow skins that you can peel them effortlessly with just two fingers!",
      "description": "Elaichi Banana (lovingly called Velchi Kela in Marathi) is the special sweet miniature banana of Maharashtra! Named after cardamom (Elaichi) because of its wonderful sweet aroma, these little bananas are firm, creamy, and bursting with honeyed natural sugar. They are the absolute favorite tiffin box fruit for school children across Mumbai, Pune, and all of Maharashtra.",
      "image": "elaichibanana.jpg",
      "model": "elaichibanana.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "fruit_21",
      "type": "fruit",
      "alphabet": "E",
      "name": "Elephant Apple (Kaith / Kavat / Wood Apple)",
      "scientificName": "Limonia acidissima",
      "category": "Fruit",
      "color": "Hard Grey-Brown Woody Shell with Tangy Brown Pulp Inside",
      "taste": "Boldly tangy, sweet-and-sour, and delicious mixed with jaggery (Gud) and salt",
      "vitamins": "Loaded with Vitamin C, Riboflavin, Calcium, Phosphorus & Tummy Fiber",
      "benefits": "Strengthens tummy digestion, cools the body during hot weather & natural energy tonic",
      "season": "Autumn and Winter harvest across Maharashtra and Indian countryside trees",
      "origin": "Ancient native Indian fruit tree whose hard-shelled fruits have been enjoyed across Indian villages for millennia",
      "culinaryUses": "Famous Kavatachi Chutney (mixed with jaggery and green chillies in Maharashtra) & sweet sherbet",
      "funFact": "In Maharashtra, when you crack open a Kavat (Wood Apple), mixing the tangy brown fruit inside with sweet jaggery (Gud) creates the most mouth-watering traditional chutney!",
      "description": "Elephant Apple (known in Marathi as Kavat and in Hindi as Kaith) is a fascinating traditional Indian fruit! Covered in a hard, round grey-brown woody shell, grown-ups crack it open to reveal tangy, aromatic brown fruit pulp inside. Across Maharashtra, families love mixing fresh Kavat pulp with sweet jaggery (Gud) and salt to make Kavatachi Chutney, an unforgettable sweet-and-sour treat.",
      "image": "elephantapple.jpg",
      "model": "elephantapple.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "fruit_22",
      "type": "fruit",
      "alphabet": "E",
      "name": "Early Apple (Golden Harvest Seb)",
      "scientificName": "Malus domestica 'Golden'",
      "category": "Fruit",
      "color": "Bright Golden Yellow & Pale Green",
      "taste": "Crisp, lively, sweet-tangy, and super refreshing",
      "vitamins": "Loaded with Vitamin C, Pectin Fiber & Quick Energy",
      "benefits": "Refreshes body on warm summer days, cleans teeth & super crunchy",
      "season": "Early Summer apple harvest across northern Indian markets",
      "origin": "Early ripening golden apple variety enjoyed in Indian fruit stalls when summer arrives",
      "culinaryUses": "Fresh summer crunch snacks, fruit salad cups & homemade apple puree",
      "funFact": "Early Golden apples are the very first apples to arrive in Indian fruit markets every summer while red apples wait for autumn!",
      "description": "The Early Apple (or Golden Summer Seb) is a bright yellow apple that arrives in Indian fruit markets right at the start of summer! It has a glowing golden-yellow skin and crisp white flesh that bursts with lively, sweet-and-tangy fruit juice. Biting into one gives children a refreshing crunch and clean fruit energy on warm sunny days.",
      "image": "earlyapple.jpg",
      "model": "earlyapple.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "fruit_23",
      "type": "fruit",
      "alphabet": "E",
      "name": "European Pear (Nashpati / Babugosha)",
      "scientificName": "Pyrus communis",
      "category": "Fruit",
      "color": "Golden Green & Bartlett Yellow",
      "taste": "Soft, buttery-juicy, and sweet like honeyed orchard nectar",
      "vitamins": "Rich in Vitamin C, Soluble Fiber, Potassium & Fruit Antioxidants",
      "benefits": "Keeps tummy digestion super smooth, quenches thirst & gives clean energy",
      "season": "Late Summer and Autumn harvest (Sold as Nashpati / Babugosha across Indian markets)",
      "origin": "Beloved bell-shaped sweet pear grown across Indian hill orchards (Simla/Kashmir)",
      "culinaryUses": "Soft lunchbox fruit wedges, fruit custard topping & fresh sweet snacking",
      "funFact": "In India, soft sweet pears are lovingly called 'Babugosha' because their fruit flesh is so buttery and soft it melts right in your mouth!",
      "description": "The Sweet Pear (known across all Indian fruit stalls as Nashpati or Babugosha) is a classic bell-shaped fruit loved by children and adults across the country! When ripe, its golden-green skin yields to a super soft, buttery interior that drips with sweet, honeyed pear juice. It is super easy to chew and packed with healthy plant fiber for growing kids.",
      "image": "europeanpear.jpg",
      "model": "europeanpear.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "fruit_24",
      "type": "fruit",
      "alphabet": "E",
      "name": "Eggplant (Brinjal / Baingan / Vangi)",
      "scientificName": "Solanum melongena",
      "category": "Fruit",
      "color": "Glossy Deep Purple Skin with Creamy White Inside",
      "taste": "Mild, savory, soft, and absorbs yummy masala and tomato flavors when cooked",
      "vitamins": "Rich in Fiber, Potassium, Manganese & Nasunin Brain Antioxidants",
      "benefits": "Keeps brain cells sharp, aids heart circulation & very healthy and filling Indian dish",
      "season": "Year-round harvest across Maharashtra and Indian vegetable gardens",
      "origin": "Native Indian garden plant cultivated across Indian villages and farms for over 4,000 years",
      "culinaryUses": "Maharashtra's famous Bharli Vangi (stuffed brinjal), Baingan Bharta, Vada Pav accompaniment & curry",
      "funFact": "Even though we cook Brinjal (Baingan / Vangi) like a savory vegetable with Indian spices, botanically it is a true berry fruit because it has tiny seeds inside!",
      "description": "Eggplant (known across India as Brinjal or Baingan, and lovingly celebrated in Maharashtra as Vangi!) is one of India's most famous and glossy purple garden fruits! While cooked as a savory vegetable in Maharashtra's world-famous 'Bharli Vangi' (stuffed brinjal masala) or smoky 'Baingan Bharta', scientists classify it as a true fruit because it grows from a garden flower and holds little seeds inside.",
      "image": "eggplant.jpg",
      "model": "eggplant.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "fruit_25",
      "type": "fruit",
      "alphabet": "F",
      "name": "Fig (Anjeer / Sweet Pune Fig)",
      "scientificName": "Ficus carica",
      "category": "Fruit",
      "color": "Soft Purple & Green with Rose Pink Inside",
      "taste": "Jammy, sweet, honeyed, and soft with tiny crunchy seeds",
      "vitamins": "Rich in Calcium (for strong bones), Iron, Potassium & Fiber",
      "benefits": "Builds super strong bones and teeth, keeps tummy happy & gives natural energy",
      "season": "Summer and Autumn harvest across Maharashtra farms (Famous Pune Anjeer)",
      "origin": "Grown across Maharashtra's Purandar hills for generations with official GI Tag",
      "culinaryUses": "Fresh sweet snacks, Anjeer jam, Kaju Anjeer barfi & dried energy treats",
      "funFact": "A fig is actually a hollow pod filled with hundreds of tiny hidden flowers that bloom inside!",
      "description": "Figs (known across India and Maharashtra as Anjeer) are soft, tear-shaped purple or green fruits that are famous across the country for building super strong bones! When you slice open an Anjeer, the inside looks like rose-pink jam filled with hundreds of tiny, delicate seeds that give a fun gentle crunch. They have more natural calcium than almost any other fruit.",
      "image": "fig.jpg",
      "model": "fig.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "fruit_26",
      "type": "fruit",
      "alphabet": "F",
      "name": "Falsa (Phalsa — Indian Sherbet Berry)",
      "scientificName": "Grewia asiatica",
      "category": "Fruit",
      "color": "Tiny Dark Purple & Crimson Red Berries",
      "taste": "Exciting sweet-and-sour, tangy, and bursting with refreshing berry juice",
      "vitamins": "Loaded with Vitamin C, Iron, Sodium, Potassium & Cooling Summer Antioxidants",
      "benefits": "India's ultimate summer heat quencher, purifies blood & instantly cools the body",
      "season": "Indian Summer harvest (May and June across Indian fruit carts)",
      "origin": "Ancient native Indian berry tree whose cooling fruits have refreshed Indian summers for centuries",
      "culinaryUses": "Fresh snacking with Kala Namak (black salt) & famous cooling Phalsa ka Sharbat juice",
      "funFact": "During hot Indian summers, street vendors sell little leaf bowls of fresh Phalsa berries sprinkled with black salt to keep everyone cool and hydrated!",
      "description": "Falsa (also spelled Phalsa) is one of India's most exciting and refreshing summer berries! These tiny, dark purple-red berries arrive on Indian fruit carts right in the middle of summer. When tossed with a pinch of black salt (Kala Namak) or squeezed into cold water with sugar to make 'Phalsa ka Sharbat,' every sip delivers a magical sweet-and-sour splash that cools the body instantly.",
      "image": "falsa.jpg",
      "model": "falsa.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "fruit_27",
      "type": "fruit",
      "alphabet": "F",
      "name": "Fuji Apple (Sweet Crispy Seb)",
      "scientificName": "Malus domestica 'Fuji'",
      "category": "Fruit",
      "color": "Rosy Pink & Yellow Striped Blush",
      "taste": "Extra sweet, honey-like, super crisp, and bursting with apple juice",
      "vitamins": "Abundant in Vitamin C, Potassium, Quercetin & Natural Soluble Fiber",
      "benefits": "Gives clean playground energy, cleans teeth & super refreshing snack",
      "season": "Available super crisp across every Indian fruit shop all year round",
      "origin": "Globally famous sweet apple variety prized in Indian fruit markets for its high crunch",
      "culinaryUses": "Crisp school tiffin apple slices, fruit custard, caramel dipping & fresh snacks",
      "funFact": "Fuji apples have more natural honeyed sugar and crispness than almost any other apple in the world!",
      "description": "The Fuji Apple (sold across Indian fruit markets as Sweet Crispy Seb) is famous as the undisputed king of crunch and natural honeyed sweetness! It has a beautiful rosy-pink and yellow striped skin and an incredibly firm, juicy inside that snaps with every single bite. Because it stays crisp and sweet for months, it is the number one favorite lunchbox apple for kids across India.",
      "image": "fujiapple.jpg",
      "model": "fujiapple.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "fruit_28",
      "type": "fruit",
      "alphabet": "F",
      "name": "Forest Strawberry (Mahabaleshwar Strawberry)",
      "scientificName": "Fragaria ananassa / Fragaria vesca",
      "category": "Fruit",
      "color": "Glowing Ruby Red with Tiny Golden Seed Dots",
      "taste": "Super sweet, juicy, aromatic, and bursting with red strawberry nectar",
      "vitamins": "Supercharged with Vitamin C, Folate, Manganese & Red Berry Antioxidants",
      "benefits": "Boosts immune defense against coughs, keeps brain sharp & makes cheeks pink and glowing",
      "season": "Winter and Spring hill station harvest across Mahabaleshwar and Panchgani",
      "origin": "Farmed with great pride across Maharashtra's Mahabaleshwar hill station (85% of India's strawberries!)",
      "culinaryUses": "Mahabaleshwar Strawberry Cream with ice cream, milkshake, jam & fresh sweet snacking",
      "funFact": "Maharashtra's Mahabaleshwar and Panchgani hill stations grow over 85% of all the sweet, juicy red strawberries enjoyed across all of India!",
      "description": "Forest Strawberry (including the world-famous sweet strawberries grown right in Maharashtra's Mahabaleshwar and Panchgani hill stations!) is every child's favorite red jewel fruit! Ripe red strawberries are packed with Vitamin C and an intoxicating, sweet aroma. Visiting Mahabaleshwar to enjoy fresh ruby-red strawberries topped with thick, sweet cream or ice cream is one of Maharashtra's happiest family traditions.",
      "image": "foreststrawberry.jpg",
      "model": "foreststrawberry.glb",
      "hasRealModel": false,
      "hasRealImage": false
    },
    {
      "id": "fruit_29",
      "type": "fruit",
      "alphabet": "F",
      "name": "Fresh Lime (Nimbu / Limbu)",
      "scientificName": "Citrus aurantiifolia",
      "category": "Fruit",
      "color": "Bright Emerald Green & Sunshine Yellow",
      "taste": "Tangy, zesty, sour, and super refreshing when squeezed into water",
      "vitamins": "Supercharged with Vitamin C, Citrus Bioflavonoids & Natural Cooling Power",
      "benefits": "Protects against summer heatstroke, boosts immunity instantly & refreshes the spirit",
      "season": "Harvested and available across every Indian market stall 365 days a year",
      "origin": "Ancient native Indian citrus fruit essential to every Indian household and recipe",
      "culinaryUses": "India's favorite Nimbu Pani (lemonade with sugar, salt and cumin), poha squeeze & pickles",
      "funFact": "In Maharashtra and India, squeezing fresh Limbu juice over warm Poha or making chilled Nimbu Pani is everyone's daily dose of sunshine and Vitamin C!",
      "description": "Fresh Lime (called Nimbu in Hindi and Limbu in Marathi) is the most important, refreshing everyday citrus fruit across every single Indian home and kitchen! While sour to eat all by itself, squeezing fresh Limbu into a glass of cool water with a spoonful of sugar and a pinch of black salt creates 'Nimbu Pani,' India's most delicious and famous thirst-quencher to keep everyone happy and hydrated.",
      "image": "nimbu.jpg",
      "model": "nimbu.glb",
      "hasRealModel": false,
      "hasRealImage": false
    }
  ]
};
