[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, content-type, Authorization"

[[headers]]
  for = "/model/*"
  [headers.values]
    Content-Type = "model/gltf-binary"
    Access-Control-Allow-Origin = "*"
